"""
This type stub file was generated by pyright.
"""

def get_ipv6(dns_name): # -> str | None:
    ...

def get_parser(): # -> ArgumentParser:
    """The argument parser for the command line interface.

    :return: A ArgumentParser object.
    :rtype: argparse.ArgumentParser
    """
    ...

def main(): # -> None:
    ...

if __name__ == '__main__':
    ...
