"""
This type stub file was generated by pyright.
"""

def check_for_duplicates(path): ...
def get_parser():  # -> ArgumentParser:
    """The argument parser for the command line interface.

    :return: A ArgumentParser object.
    :rtype: argparse.ArgumentParser
    """
    ...

def main(): ...

if __name__ == "__main__": ...
