"""
This type stub file was generated by pyright.
"""

run = ...
dependencies = ...
tmp_dir = ...

def do_pdftk_cat_first_page(pdf_file):  # -> str:
    """The cmd_args magick identify is very slow on page pages hence it
    examines every page. We extract the first page to get some informations
    about the dimensions of the PDF file."""
    ...

def do_magick_identify_dimensions(pdf_file):  # -> dict[str, int]:
    """"""
    ...

def get_pdf_info(pdf_file): ...
def convert_image_to_pdf_page(image, image_width, pdf_width, pdf_density_x): ...
def assemble_pdf(main_pdf, insert_pdf, page_count, page_number, mode=..., position=...):
    """
    :param str main_pdf: Path of the main PDF file.
    :param str insert_pdf: Path of the PDF file to insert into the main PDF
      file.
    :param int page_count: Page count of the main PDF file.
    :param int page_number: Page number in the main PDF file to add / to
      replace the insert PDF file.
    :param string mode: Mode how the PDF to insert is treated. Possible choices
      are: `add` or `replace`.
    :param str position: Possible choices: `before` and `after`
    """
    ...

def get_parser():  # -> ArgumentParser:
    """The argument parser for the cmd_args line interface.

    :return: A ArgumentParser object.
    :rtype: argparse.ArgumentParser
    """
    ...

def main(): ...

if __name__ == "__main__": ...
