"""
This type stub file was generated by pyright.
"""

def mac_to_eui64(mac, prefix=...): # -> str | None:
    '''
    Convert a MAC address to a EUI64 address
    or, with prefix provided, a full IPv6 address
    '''
    ...

def get_parser(): # -> ArgumentParser:
    """The argument parser for the command line interface.

    :return: A ArgumentParser object.
    :rtype: argparse.ArgumentParser
    """
    ...

def main(): # -> None:
    ...

if __name__ == '__main__':
    ...
